
window.POE_MAIN = {
    "metadata": {
        "dataset_name": "rwanda_uganda_points_of_entry_2026_mobile_filterable",
        "schema_version": "2.0.0",
        "created_from_user_supplied_text_on": "2026-03-19",
        "countries": [
            "Rwanda",
            "Uganda"
        ],
        "country_entry_counts": {
            "Rwanda": 33,
            "Uganda": 44,
            "total": 77
        },
        "primary_filter_fields": [
            "country",
            "province",
            "admin_level_1",
            "admin_level_1_type",
            "district",
            "poe_name",
            "poe_type",
            "transport_mode",
            "regional_cluster_or_rpheoc",
            "is_national_level",
            "is_major_entry",
            "is_recommended_osbp"
        ],
        "cross_country_mapping_note": "For app consistency, the field `province` is used for both countries. In Uganda, `province` stores the RPHEOC/PHEOC grouping because Uganda has no province layer in this dataset.",
        "rwanda_source_count_claim": 27,
        "rwanda_parsed_entry_count": 33,
        "rwanda_count_discrepancy_note": "The supplied text says there are 27 official POEs, but the enumerated list contains 33 entries when parsed item-by-item. One location also appears under an overlap note involving Rusizi District.",
        "data_quality_notes": [
            "This file merges the previously structured Rwanda dataset with the user-supplied Uganda dataset.",
            "Uganda uses RPHEOC/PHEOC as the province-equivalent administrative grouping for filtering.",
            "Uganda POE type and transport mode were derived from POE names using deterministic naming rules: Airport -> airport/air, Airstrip -> airstrip/air, Port -> port/water, Island -> island_entry/water, otherwise land_border/land.",
            "Border-country fields for Uganda were left null because the user-supplied Uganda list did not specify neighboring countries."
        ]
    },
    "traveler_notes": {
        "uganda_route_tip": {
            "recommended_poe": "Kagitumba Land Border",
            "note": "Often recommended as the fastest One-Stop Border Post (OSBP) for travel between Rwanda and Uganda."
        },
        "cargo_route_tip": {
            "recommended_poe": "Gatuna Land Border",
            "note": "Remains the primary route for heavy cargo."
        }
    },
    "administrative_groups": [
        {
            "country": "Rwanda",
            "admin_level_1": "City of Kigali",
            "admin_level_1_type": "province",
            "districts": [
                "Kicukiro District"
            ]
        },
        {
            "country": "Rwanda",
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "districts": [
                "Bugesera District",
                "Nyagatare District",
                "Kirehe District",
                "Gatsibo District"
            ]
        },
        {
            "country": "Rwanda",
            "admin_level_1": "Northern Province",
            "admin_level_1_type": "province",
            "districts": [
                "Gicumbi District",
                "Burera District",
                "Musanze District"
            ]
        },
        {
            "country": "Rwanda",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "districts": [
                "Rubavu District",
                "Rusizi District",
                "Karongi District",
                "Rutsiro District",
                "Nyamasheke District",
                "Nyamagabe District"
            ]
        },
        {
            "country": "Rwanda",
            "admin_level_1": "Southern Province",
            "admin_level_1_type": "province",
            "districts": [
                "Nyaruguru District",
                "Rusizi District (Overlap)",
                "Huye District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Koboko District",
                "Moyo District",
                "Nebbi District",
                "Zombo District",
                "Arua District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Kasese District",
                "Bundibugyo District",
                "Ntoroko District",
                "Kanungu District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Gulu RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Amuru District",
                "Lamwo District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Hoima RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Buliisa District",
                "Hoima District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Jinja RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Jinja District",
                "Namayingo District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Kabale District",
                "Kisoro District",
                "Ntungamo District",
                "Isingiro District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Kampala RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Kampala District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Masaka RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Rakai District",
                "Kyotera District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "Mbale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Busia District",
                "Tororo District",
                "Namisindwa District",
                "Bukwo District"
            ]
        },
        {
            "country": "Uganda",
            "admin_level_1": "National PHEOC",
            "admin_level_1_type": "PHEOC",
            "districts": [
                "Wakiso District"
            ]
        }
    ],
    "poes": [
        {
            "id": "RW-KGL-KIC-KIA-001",
            "country": "Rwanda",
            "province": "City of Kigali",
            "district": "Kicukiro District",
            "poe_name": "Kigali International Airport",
            "poe_code": "KGL",
            "poe_type": "airport",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Primary air gateway for the country.",
            "source_province_group": "City of Kigali",
            "source_url": "https://www.migration.gov.rw/our-services/border-management",
            "admin_level_1": "City of Kigali",
            "admin_level_1_type": "province",
            "district_raw": "Kicukiro District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-BUG-BIA-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Bugesera District",
            "poe_name": "Bugesera International Airport",
            "poe_code": null,
            "poe_type": "airport",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "New flagship airport.",
            "source_province_group": "Eastern Province",
            "source_url": "https://apta-africa.com/2023/08/09/ambitious-new-rwandan-airport-to-open-in-2026/",
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Bugesera District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-BUG-NEM-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Bugesera District",
            "poe_name": "Nemba Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Eastern Province",
            "source_url": null,
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Bugesera District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-BUG-NAS-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Bugesera District",
            "poe_name": "Nemba Airstrip",
            "poe_code": null,
            "poe_type": "airstrip",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Eastern Province",
            "source_url": null,
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Bugesera District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-NYA-KLB-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Nyagatare District",
            "poe_name": "Kagitumba Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": "Uganda",
            "is_major_entry": true,
            "is_recommended_osbp": true,
            "critical_details": "Often recommended as the fastest One-Stop Border Post (OSBP) for travel between Rwanda and Uganda.",
            "source_province_group": "Eastern Province",
            "source_url": "https://www.visitrwandasafaritours.com/kagitumba-border-post/",
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyagatare District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-NYA-BLB-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Nyagatare District",
            "poe_name": "Buziba Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Eastern Province",
            "source_url": "https://www.africangorilla.com/information/list-of-rwanda-land-border-posts/",
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyagatare District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-NYA-RLB-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Nyagatare District",
            "poe_name": "Rwempasha Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Eastern Province",
            "source_url": "https://www.africangorilla.com/information/list-of-rwanda-land-border-posts/",
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyagatare District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-KIR-RLB-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Kirehe District",
            "poe_name": "Rusumo Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": "Tanzania",
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Key trade bridge to Tanzania.",
            "source_province_group": "Eastern Province",
            "source_url": "https://www.mininfra.gov.rw/updates/news-details/rehabilitation-and-widening-of-kagitumba-kayonza-rusumo-road-project-in-good-progress",
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Kirehe District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-EST-GAT-GAS-001",
            "country": "Rwanda",
            "province": "Eastern Province",
            "district": "Gatsibo District",
            "poe_name": "Gabiro Airstrip",
            "poe_code": null,
            "poe_type": "airstrip",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Eastern Province",
            "source_url": null,
            "admin_level_1": "Eastern Province",
            "admin_level_1_type": "province",
            "district_raw": "Gatsibo District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-NOR-GIC-GLB-001",
            "country": "Rwanda",
            "province": "Northern Province",
            "district": "Gicumbi District",
            "poe_name": "Gatuna Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Busiest commercial land border. Primary route for heavy cargo.",
            "source_province_group": "Northern Province",
            "source_url": "https://www.africangorilla.com/information/list-of-rwanda-land-border-posts/",
            "admin_level_1": "Northern Province",
            "admin_level_1_type": "province",
            "district_raw": "Gicumbi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-NOR-BUR-CLB-001",
            "country": "Rwanda",
            "province": "Northern Province",
            "district": "Burera District",
            "poe_name": "Cyanika Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Northern Province",
            "source_url": "https://bambooecotours.com/kyanika-uganda-rwanda-land-border-crossing/",
            "admin_level_1": "Northern Province",
            "admin_level_1_type": "province",
            "district_raw": "Burera District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-NOR-BUR-BLB-001",
            "country": "Rwanda",
            "province": "Northern Province",
            "district": "Burera District",
            "poe_name": "Buhita Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Northern Province",
            "source_url": null,
            "admin_level_1": "Northern Province",
            "admin_level_1_type": "province",
            "district_raw": "Burera District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-NOR-MUS-RAS-001",
            "country": "Rwanda",
            "province": "Northern Province",
            "district": "Musanze District",
            "poe_name": "Ruhengeri Airstrip",
            "poe_code": null,
            "poe_type": "airstrip",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Northern Province",
            "source_url": null,
            "admin_level_1": "Northern Province",
            "admin_level_1_type": "province",
            "district_raw": "Musanze District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUB-LCO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rubavu District",
            "poe_name": "La Corniche Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Gisenyi crossing.",
            "source_province_group": "Western Province",
            "source_url": "https://www.migration.gov.rw/our-services/border-management",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rubavu District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUB-PLB-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rubavu District",
            "poe_name": "Poids Lourds Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Gisenyi crossing.",
            "source_province_group": "Western Province",
            "source_url": "https://www.migration.gov.rw/our-services/border-management",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rubavu District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUB-RPO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rubavu District",
            "poe_name": "Rubavu Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Lake Kivu water-based entry point.",
            "source_province_group": "Western Province",
            "source_url": "https://www.migration.gov.rw/our-services/border-management",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rubavu District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUB-KLB-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rubavu District",
            "poe_name": "Kabuhanga Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rubavu District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUB-GAP-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rubavu District",
            "poe_name": "Gisenyi Airport",
            "poe_code": null,
            "poe_type": "airport",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rubavu District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUS-KIA-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rusizi District",
            "poe_name": "Kamembe International Airport",
            "poe_code": "KME",
            "poe_type": "airport",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": "https://rac.co.rw/about-us-1/airports-1",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rusizi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUS-R1B-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rusizi District",
            "poe_name": "Rusizi I Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": "https://rwanda.iom.int/immigration-and-border-governance",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rusizi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUS-R2B-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rusizi District",
            "poe_name": "Rusizi II Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": "https://rwanda.iom.int/immigration-and-border-governance",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rusizi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUS-RPO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rusizi District",
            "poe_name": "Rusizi Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Lake Kivu water-based entry point.",
            "source_province_group": "Western Province",
            "source_url": "https://www.migration.gov.rw/our-services/border-management",
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rusizi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUS-BLB-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rusizi District",
            "poe_name": "Bugarama Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rusizi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-KAR-KPO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Karongi District",
            "poe_name": "Karongi Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Lake Kivu water-based entry point.",
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Karongi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-KAR-RPO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Karongi District",
            "poe_name": "Ruganda Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Lake Kivu water-based entry point.",
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Karongi District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-RUT-NPO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Rutsiro District",
            "poe_name": "Nkora Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Lake Kivu water-based entry point.",
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Rutsiro District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-NYA-NPO-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Nyamasheke District",
            "poe_name": "Nyamasheke Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Lake Kivu water-based entry point.",
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyamasheke District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-WES-NYM-BLB-001",
            "country": "Rwanda",
            "province": "Western Province",
            "district": "Nyamagabe District",
            "poe_name": "Bweyeye Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Western Province",
            "source_url": null,
            "admin_level_1": "Western Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyamagabe District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-SOU-NYA-AHB-001",
            "country": "Rwanda",
            "province": "Southern Province",
            "district": "Nyaruguru District",
            "poe_name": "Akanyaru Haut Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Region primarily borders Burundi; some borders in this region have experienced periodic operational changes.",
            "source_province_group": "Southern Province",
            "source_url": null,
            "admin_level_1": "Southern Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyaruguru District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-SOU-NYA-ABB-001",
            "country": "Rwanda",
            "province": "Southern Province",
            "district": "Nyaruguru District",
            "poe_name": "Akanyaru Bas Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Region primarily borders Burundi; some borders in this region have experienced periodic operational changes.",
            "source_province_group": "Southern Province",
            "source_url": null,
            "admin_level_1": "Southern Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyaruguru District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-SOU-NYA-NLB-001",
            "country": "Rwanda",
            "province": "Southern Province",
            "district": "Nyaruguru District",
            "poe_name": "Nshili Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": "Region primarily borders Burundi; some borders in this region have experienced periodic operational changes.",
            "source_province_group": "Southern Province",
            "source_url": null,
            "admin_level_1": "Southern Province",
            "admin_level_1_type": "province",
            "district_raw": "Nyaruguru District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-SOU-RUS-RLB-001",
            "country": "Rwanda",
            "province": "Southern Province",
            "district": "Rusizi District (Overlap)",
            "poe_name": "Ruhwa Land Border",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": "DRC/Burundi",
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "critical_details": "Located at the junction of Rwanda, DRC, and Burundi. Source text lists this under an overlap note.",
            "source_province_group": "Southern Province",
            "source_url": null,
            "admin_level_1": "Southern Province",
            "admin_level_1_type": "province",
            "district_raw": "Rusizi District (Overlap)",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "RW-SOU-HUY-BAS-001",
            "country": "Rwanda",
            "province": "Southern Province",
            "district": "Huye District",
            "poe_name": "Butare Airstrip",
            "poe_code": null,
            "poe_type": "airstrip",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "critical_details": null,
            "source_province_group": "Southern Province",
            "source_url": null,
            "admin_level_1": "Southern Province",
            "admin_level_1_type": "province",
            "district_raw": "Huye District",
            "is_national_level": false,
            "regional_cluster_or_rpheoc": null,
            "source_origin": "User-supplied Rwanda POE list"
        },
        {
            "id": "UG-GUL-AMU-ELE-001",
            "country": "Uganda",
            "province": "Gulu RPHEOC",
            "admin_level_1": "Gulu RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Amuru District",
            "district_raw": "Amuru",
            "poe_name": "Elegu / Atiak",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Gulu RPHEOC",
            "critical_details": "Mapped to Gulu RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Gulu RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-GUL-LAM-NGO-001",
            "country": "Uganda",
            "province": "Gulu RPHEOC",
            "admin_level_1": "Gulu RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Lamwo District",
            "district_raw": "Lamwo",
            "poe_name": "Ngoromoro",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Gulu RPHEOC",
            "critical_details": "Mapped to Gulu RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Gulu RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-GUL-LAM-MAD-001",
            "country": "Uganda",
            "province": "Gulu RPHEOC",
            "admin_level_1": "Gulu RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Lamwo District",
            "district_raw": "Lamwo",
            "poe_name": "Madi Opei",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Gulu RPHEOC",
            "critical_details": "Mapped to Gulu RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Gulu RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-KOB-ORA-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Koboko District",
            "district_raw": "Koboko",
            "poe_name": "Oraba",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-MOY-AFO-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Moyo District",
            "district_raw": "Moyo",
            "poe_name": "Afogi",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-NEB-GOL-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Nebbi District",
            "district_raw": "Nebbi",
            "poe_name": "Goli",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-NEB-DEI-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Nebbi District",
            "district_raw": "Nebbi",
            "poe_name": "Dei",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-ZOM-PAI-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Zombo District",
            "district_raw": "Zombo",
            "poe_name": "Paidha",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-ZOM-PAD-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Zombo District",
            "district_raw": "Zombo",
            "poe_name": "Padea",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-ARU-VUR-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Arua District",
            "district_raw": "Arua",
            "poe_name": "Vurra",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-ARU-ODR-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Arua District",
            "district_raw": "Arua",
            "poe_name": "Odramachaka",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-ARU-LIA-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Arua District",
            "district_raw": "Arua",
            "poe_name": "Lia",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-ARU-ARU-ARU-001",
            "country": "Uganda",
            "province": "Arua RPHEOC",
            "admin_level_1": "Arua RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Arua District",
            "district_raw": "Arua",
            "poe_name": "Arua Airstrip",
            "poe_code": null,
            "poe_type": "airstrip",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Arua RPHEOC",
            "critical_details": "Mapped to Arua RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Arua RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-MBA-BUS-BUS-001",
            "country": "Uganda",
            "province": "Mbale RPHEOC",
            "admin_level_1": "Mbale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Busia District",
            "district_raw": "Busia",
            "poe_name": "Busia",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Mbale RPHEOC",
            "critical_details": "Mapped to Mbale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Mbale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-MBA-TOR-MAL-001",
            "country": "Uganda",
            "province": "Mbale RPHEOC",
            "admin_level_1": "Mbale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Tororo District",
            "district_raw": "Tororo",
            "poe_name": "Malaba",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Mbale RPHEOC",
            "critical_details": "Mapped to Mbale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Mbale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-MBA-NAM-LWA-001",
            "country": "Uganda",
            "province": "Mbale RPHEOC",
            "admin_level_1": "Mbale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Namisindwa District",
            "district_raw": "Namisindwa",
            "poe_name": "Lwakhakha",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Mbale RPHEOC",
            "critical_details": "Mapped to Mbale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Mbale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-MBA-BUK-SUA-001",
            "country": "Uganda",
            "province": "Mbale RPHEOC",
            "admin_level_1": "Mbale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Bukwo District",
            "district_raw": "Bukwo",
            "poe_name": "Suam River",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Mbale RPHEOC",
            "critical_details": "Mapped to Mbale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Mbale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-JIN-JIN-KIM-001",
            "country": "Uganda",
            "province": "Jinja RPHEOC",
            "admin_level_1": "Jinja RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Jinja District",
            "district_raw": "Jinja",
            "poe_name": "Kimaka Airstrip",
            "poe_code": null,
            "poe_type": "airstrip",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Jinja RPHEOC",
            "critical_details": "Mapped to Jinja RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Jinja RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-JIN-JIN-JIN-001",
            "country": "Uganda",
            "province": "Jinja RPHEOC",
            "admin_level_1": "Jinja RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Jinja District",
            "district_raw": "Jinja",
            "poe_name": "Jinja Port",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Jinja RPHEOC",
            "critical_details": "Mapped to Jinja RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Jinja RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-JIN-NAM-LOL-001",
            "country": "Uganda",
            "province": "Jinja RPHEOC",
            "admin_level_1": "Jinja RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Namayingo District",
            "district_raw": "Namayingo",
            "poe_name": "Lolwe Island",
            "poe_code": null,
            "poe_type": "island_entry",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Jinja RPHEOC",
            "critical_details": "Mapped to Jinja RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Jinja RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-JIN-NAM-SIN-001",
            "country": "Uganda",
            "province": "Jinja RPHEOC",
            "admin_level_1": "Jinja RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Namayingo District",
            "district_raw": "Namayingo",
            "poe_name": "Singulu Island",
            "poe_code": null,
            "poe_type": "island_entry",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Jinja RPHEOC",
            "critical_details": "Mapped to Jinja RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Jinja RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-KAB-KAT-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kabale District",
            "district_raw": "Kabale",
            "poe_name": "Katuna",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-KAB-KAM-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kabale District",
            "district_raw": "Kabale",
            "poe_name": "Kamwezi",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-KIS-CYA-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kisoro District",
            "district_raw": "Kisoro",
            "poe_name": "Cyanika",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-KIS-BUN-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kisoro District",
            "district_raw": "Kisoro",
            "poe_name": "Bunagana",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-NTU-MIR-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Ntungamo District",
            "district_raw": "Ntungamo",
            "poe_name": "Mirama Hills",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-NTU-KIZ-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Ntungamo District",
            "district_raw": "Ntungamo",
            "poe_name": "Kizinga",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-ISI-KIK-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Isingiro District",
            "district_raw": "Isingiro",
            "poe_name": "Kikagati",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAB-ISI-BUG-001",
            "country": "Uganda",
            "province": "Kabale RPHEOC",
            "admin_level_1": "Kabale RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Isingiro District",
            "district_raw": "Isingiro",
            "poe_name": "Bugango",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kabale RPHEOC",
            "critical_details": "Mapped to Kabale RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kabale RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-KAS-MPO-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kasese District",
            "district_raw": "Kasese",
            "poe_name": "Mpondwe",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-KAS-KAY-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kasese District",
            "district_raw": "Kasese",
            "poe_name": "Kayanja",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-BUN-BUS-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Bundibugyo District",
            "district_raw": "Bundibugyo",
            "poe_name": "Busunga",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-NTO-NTO-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Ntoroko District",
            "district_raw": "Ntoroko",
            "poe_name": "Ntoroko",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-NTO-LWE-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Ntoroko District",
            "district_raw": "Ntoroko",
            "poe_name": "Lwebisengo",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-KAN-ISH-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kanungu District",
            "district_raw": "Kanungu",
            "poe_name": "Ishasha",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-FOR-KAN-BUT-001",
            "country": "Uganda",
            "province": "Fort Portal RPHEOC",
            "admin_level_1": "Fort Portal RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kanungu District",
            "district_raw": "Kanungu",
            "poe_name": "Butogota",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Fort Portal RPHEOC",
            "critical_details": "Mapped to Fort Portal RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Fort Portal RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-HOI-BUL-BUT-001",
            "country": "Uganda",
            "province": "Hoima RPHEOC",
            "admin_level_1": "Hoima RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Buliisa District",
            "district_raw": "Buliisa",
            "poe_name": "Butiaba",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Hoima RPHEOC",
            "critical_details": "Mapped to Hoima RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Hoima RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-HOI-BUL-WAN-001",
            "country": "Uganda",
            "province": "Hoima RPHEOC",
            "admin_level_1": "Hoima RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Buliisa District",
            "district_raw": "Buliisa",
            "poe_name": "Wanseko",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Hoima RPHEOC",
            "critical_details": "Mapped to Hoima RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Hoima RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-HOI-HOI-KAI-001",
            "country": "Uganda",
            "province": "Hoima RPHEOC",
            "admin_level_1": "Hoima RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Hoima District",
            "district_raw": "Hoima",
            "poe_name": "Kaiso-Tonya",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Hoima RPHEOC",
            "critical_details": "Mapped to Hoima RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Hoima RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-HOI-HOI-SEB-001",
            "country": "Uganda",
            "province": "Hoima RPHEOC",
            "admin_level_1": "Hoima RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Hoima District",
            "district_raw": "Hoima",
            "poe_name": "Sebagoro",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Hoima RPHEOC",
            "critical_details": "Mapped to Hoima RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Hoima RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-NAT-WAK-ENT-001",
            "country": "Uganda",
            "province": "National PHEOC",
            "admin_level_1": "National PHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Wakiso District",
            "district_raw": "Wakiso",
            "poe_name": "Entebbe International Airport",
            "poe_code": null,
            "poe_type": "airport",
            "transport_mode": "air",
            "border_country": null,
            "is_major_entry": true,
            "is_recommended_osbp": false,
            "is_national_level": true,
            "regional_cluster_or_rpheoc": "National PHEOC",
            "critical_details": "National-level PHEOC grouping used as the province-equivalent administrative layer for app filtering.",
            "source_province_group": "National PHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-KAM-KAM-POR-001",
            "country": "Uganda",
            "province": "Kampala RPHEOC",
            "admin_level_1": "Kampala RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kampala District",
            "district_raw": "Kampala",
            "poe_name": "Port Bell",
            "poe_code": null,
            "poe_type": "port",
            "transport_mode": "water",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Kampala RPHEOC",
            "critical_details": "Mapped to Kampala RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Kampala RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-MAS-RAK-MUT-001",
            "country": "Uganda",
            "province": "Masaka RPHEOC",
            "admin_level_1": "Masaka RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Rakai District",
            "district_raw": "Rakai",
            "poe_name": "Mutukula",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Masaka RPHEOC",
            "critical_details": "Mapped to Masaka RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Masaka RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        },
        {
            "id": "UG-MAS-KYO-KAN-001",
            "country": "Uganda",
            "province": "Masaka RPHEOC",
            "admin_level_1": "Masaka RPHEOC",
            "admin_level_1_type": "PHEOC",
            "district": "Kyotera District",
            "district_raw": "Kyotera",
            "poe_name": "Kansensero",
            "poe_code": null,
            "poe_type": "land_border",
            "transport_mode": "land",
            "border_country": null,
            "is_major_entry": false,
            "is_recommended_osbp": false,
            "is_national_level": false,
            "regional_cluster_or_rpheoc": "Masaka RPHEOC",
            "critical_details": "Mapped to Masaka RPHEOC as the province-equivalent administrative layer for Uganda in the mobile app.",
            "source_province_group": "Masaka RPHEOC",
            "source_url": null,
            "source_origin": "User-supplied Uganda POE list"
        }
    ]
};
